### ISSUE TITLE
Plugin not working in WebUI

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-plugin-autoorganize#65] opened 2021-06-01 14:00 UTC
win10 (clean install in vm)
clean install of jellyfin 10.7.5

settings in UI not visible
```
Uncaught ReferenceError: define is not defined
    <anonymous> http://127.0.0.1:8096/web/configurationpage?name=AutoOrganizeLogJs:1
```

**Comment by crobibero** [comment] 2021-06-01 14:02
Duplicate of https://github.com/jellyfin/jellyfin-plugin-autoorganize/issues/58

**Closed as completed by crobibero** 2021-06-01 14:02 UTC
