### ISSUE TITLE
Config page crashes on 10.4

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-plugin-autoorganize#16] opened 2019-10-08 14:58 UTC
The following error is thrown when loading the AutoOrganize config page on 10.4.0.
```
jellyfin_1       | [14:54:38] [ERR] Error processing request
jellyfin_1       | System.MissingMethodException: Method not found: '!0[] MediaBrowser.Model.Querying.QueryResult`1.get_Items()'.
jellyfin_1       |    at Emby.AutoOrganize.Core.FileOrganizationService.GetResults(FileOrganizationResultQuery query)
jellyfin_1       |    at Emby.AutoOrganize.Api.FileOrganizationService.Get(GetFileOrganizationActivity request)
jellyfin_1       |    at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
jellyfin_1       |    at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
jellyfin_1       |    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
jellyfin_1       |    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by ptimatth** [comment] 2019-10-28 16:17
Same issue here.
Helios4 with armbian (10 Buster)

```
[2019-10-28 16:43:50.644 +01:00] [ERR] Error processing request
System.MissingMethodException: Method not found: '!0[] MediaBrowser.Model.Querying.QueryResult`1.get_Items()'.
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResults(FileOrganizationResultQuery query)
   at Emby.AutoOrganize.Api.FileOrganizationService.Get(GetFileOrganizationActivity request)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by hauntingEcho** [comment] 2019-11-08 02:53
I get the same message as ptimatth.  I'm also on a Helios4 but running Debian 9 & using Jellyfin via docker.  For some more specificity, it's when I'm going to the "Activity Log" tab.  I have not yet actually  had anything added by AutoOrganize yet, so this may be caused by mishandling an empty log.

**Comment by minakmostoles** [comment] 2019-12-06 14:17
The same problem with docker in Raspberry pi when I'm going to the "Activity Log of the pluging. I have not too yet actually had anything added.

**Comment by mark-monteiro** [comment] 2019-12-08 11:31
It looks like the issue is related to outdated dependencies in the project. I have opened PR #17 to address this, which I have tested locally and fixes the issue.

This should be a pretty critical merge, I don't think this plugin will be working for anyone on the latest Jellyfin version until this update goes out.

**Comment by mark-monteiro** [comment] 2019-12-14 22:43
[Release v5](https://github.com/jellyfin/jellyfin-plugin-autoorganize/releases/tag/v5) is out now, this should be resolved with that update.

**Comment by anthonylavado** [comment] 2019-12-15 03:08
Argh it didn’t build. I’ll have to see what’s up with it.

**Comment by anthonylavado** [comment] 2019-12-15 07:51
Built now. Try it out.

**Closed as completed** 2019-12-19 09:08 UTC
Labels: bug
