### ISSUE TITLE
[WRN] No provider metadata found

### ISSUE THREAD

**Issue by tarmtrollet** [jellyfin/jellyfin-plugin-autoorganize#20] opened 2019-12-16 20:15 UTC
Just getting this error on every episode it tries to organize. The episodes are present in tvdb, and manually moving episodes to the correct folder and re-scaning library adds metadata.
Im using version 5 of the auto oragnize plugin. Let me know if you need more info or want me to try something.
Thanks a lot for Jellyfin :)

[2019-12-16 21:09:13.959 +01:00] [ERR] Error processing request
System.Exception: No provider metadata found for ... season 6 episode 7
   at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(EpisodeFileOrganizationRequest request)

**Comment by mark-monteiro** [comment] 2019-12-17 19:30
This is a duplicate of #13. It has been resolved with this PR in the main Jellyfin repo: https://github.com/jellyfin/jellyfin/pull/2138

When the next Jellyfin release drops this should be resolved!

**Closed as completed** 2019-12-17 23:54 UTC
